-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 18d7035de5388cc7775be57f529c154bf541aab9
    hooks:
    -   id: trailing-whitespace
        files: \.(tex)$
    -   id: end-of-file-fixer
        files: \.(tex)$
